# Generated by Django 5.2.7 on 2025-12-09 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_parser', '0002_city_company_platform_remove_vacancy_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name'], 'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, help_text='City name', max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, help_text='Company name', max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('HeadHunter', 'HeadHunter'), ('SuperJob', 'SuperJob'), ('Telegram', 'Telegram')], db_index=True, help_text='Name of the job search platform', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the workplace', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City where the position is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='hh_parser.city'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company offering the position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hh_parser.company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contacts',
            field=models.CharField(blank=True, help_text='Contact information', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the vacancy was added to the system'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed job description', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(blank=True, help_text='Required education level', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, help_text='Employment type (full-time, part-time, etc.)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, help_text='Required experience level', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='platform',
            field=models.ForeignKey(blank=True, help_text='Platform where the vacancy was posted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hh_parser.platform'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='platform_vacancy_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier from the source platform', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(db_index=True, help_text='When the vacancy was published on the source platform'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary information', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, help_text='Work schedule', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, help_text='Required skills and qualifications', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(db_index=True, help_text='Job title', max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(blank=True, help_text='URL to the original vacancy posting', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, help_text='Work format (remote, office, hybrid, etc.)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-published_at', 'platform'], name='hh_parser_v_publish_c0ba5a_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['title', 'company'], name='hh_parser_v_title_ad130d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__isnull', False), ('platform_vacancy_id__isnull', False)), fields=('platform', 'platform_vacancy_id'), name='unique_platform_vacancy_id'),
        ),
    ]
