# Generated by Django 5.2.7 on 2025-10-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superjob_parser', '0003_alter_superjob_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperJob',
        ),
    ]
